# Generated by Django 3.2 on 2023-02-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='CPF',
            new_name='cpf',
        ),
    ]
