# Generated by Django 3.2 on 2023-02-21 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_cpf_client_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='CNPJ',
            new_name='cnpj',
        ),
    ]
