# Generated by Django 3.2 on 2023-02-22 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20230222_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='cep',
            field=models.CharField(default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='district',
            field=models.CharField(default='', max_length=50, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='property_number',
            field=models.CharField(default=0, max_length=5, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='uf',
            field=models.CharField(default='', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
