# Generated by Django 3.2 on 2023-02-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230222_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='public_place',
            field=models.CharField(default='', max_length=150, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='public_place',
            field=models.CharField(default='', max_length=150, verbose_name='Logradouro'),
        ),
    ]
